'use strict';
var app = angular.module('defaultApp', []);

app.service('getSFOS', function() {
    return {};
});


app.service('getSFOS2', function() {
    return {
        SETUP: {
            "sfosedt.objectMaximum": 4000,
            "sfosedt.widthInches": 10.0,
            "sfosedt.heightInches": 7.5,
            "!sfosedt.waterfallSpacing": 0,
            "!sfosedt.filefilter": "* .sfos",
            "!sfosedt.initFile": "sfos_init",
            "!sfosedt.snapGrid": "Both",
            "!sfosedt.horizontalGrid": 20,
            "!sfosedt.verticalGrid": 20,
            "sfosedt*background": "Tan",
            "sfosedt*foreground": "black",
            "sfosedt*drawingArea.background": "LightBlue",
            "sfosedt*drawingArea.foreground": "black",
            "sfosedt*scrollWin.width": 1004,
            "sfosedt*scrollWin.height": 754,
            "sfosedt.maxWidth": 1150,
            "sfosedt.maxHeight": 870,
            "sfosedt*logFrame.marginWidth": 0,
            "sfosedt*logFrame.marginHeight": 0,
            "sfosedt*logFrame.shadowType": "SHADOW_IN",
            "sfosedt*logFrame.shadowThickness": 3,
            "sfosedt*logText.background": "LightSteelBlue",
            "sfosedt*logText.text.font": "fixed",
            "sfosedt*logText.text.lines": 4,
            "sfosedt*menuCursor": "hand1",
            "sfosedt*XmToggleButtonGadget.selectColor": "Red"
        },
        //4 types of records
        //border records
        //region records
        //color records
        //marker records
        BORDERRECORDS: [{ //vector of 12 integer values
            lineIndex: 0,
            direction: 0,
            coordinate: 10,
            startLine: 0,
            endLine: 1,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 0,
            majorLabel: 0,
            minorLabel: 0
        }, {
            lineIndex: 1,
            direction: 0,
            coordinate: 100,
            startLine: 0,
            endLine: 1,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 0,
            majorLabel: 0,
            minorLabel: 0
        }, {
            lineIndex: 2,
            direction: 0,
            coordinate: 990,
            startLine: 0,
            endLine: 1,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 0,
            majorLabel: 0,
            minorLabel: 0
        }, {
            lineIndex: 0,
            direction: 1,
            coordinate: 60,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 4,
            ticMarks: 1,
            majorLabel: 1,
            minorLabel: 1
        }, {
            lineIndex: 2,
            direction: 1,
            coordinate: 70,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 16,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 9,
            direction: 1,
            coordinate: 80,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 24,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 3,
            direction: 1,
            coordinate: 80,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 10,
            direction: 1,
            coordinate: 160,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 4,
            direction: 1,
            coordinate: 233,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 5,
            direction: 1,
            coordinate: 290,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 6,
            direction: 1,
            coordinate: 385,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 1,
            minorLabel: 1
        }, {
            lineIndex: 7,
            direction: 1,
            coordinate: 680,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 1,
            ticMarks: 1,
            majorLabel: 1,
            minorLabel: 1,
        }, {
            lineIndex: 1,
            direction: 1,
            coordinate: 692,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 9,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }, {
            lineIndex: 8,
            direction: 1,
            coordinate: 692,
            startLine: 0,
            endLine: 2,
            startOffset: 0,
            endOffset: 0,
            color: 0,
            lineType: 5,
            ticMarks: 1,
            majorLabel: 3,
            minorLabel: 1
        }],
        REGION: [{
            regionIndex: 0,
            leftBorderIndex: -2,
            rightBorderIndex: -1,
            topBorderIndex: -2,
            bottomBorderIndex: -1,
            legalObjects: "cdehilmpqstv",
            regionName: "sfos page"
        }, {
            regionIndex: 2,
            leftBorderIndex: 0,
            rightBorderIndex: 1,
            topBorderIndex: 3,
            bottomBorderIndex: 10,
            legalObjects: "cdehilmpqstv",
            regionName: "spacecraft states legend",
        }, {
            regionIndex: 3,
            leftBorderIndex: 0,
            rightBorderIndex: 1,
            topBorderIndex: 4,
            bottomBorderIndex: 5,
            legalObjects: "cdehilmpqstv",
            regionname: "to mode legend"
        }, {
            regionIndex: 4,
            leftBorderIndex: 0,
            rightBorderIndex: 1,
            topBorderIndex: 5,
            bottomBorderIndex: 6,
            legalObjects: "cdehilmpqstv",
            regionName: "bar legend"
        }, {
            regionIndex: 5,
            leftBorderIndex: 0,
            rightBorderIndex: 1,
            topBorderIndex: 6,
            bottomBorderIndex: 7,
            legalObjects: "cdehilmpqstv",
            regionName: "dss legend region"
        }, {
            regionIndex: 6,
            leftBorderIndex: 1,
            rightBorderIndex: 2,
            topBorderIndex: 3,
            bottomBorderIndex: 10,
            legalObjects: "cdehilmpqstv",
            regionName: "spacecraft_states_region"
        }, {
            regionIndex: 7,
            leftBorderIndex: 1,
            rightBorderIndex: 2,
            topBorderIndex: 10,
            bottomBorderIndex: 4,
            legalObjects: "cdehilmpqstv",
            regionName: "sequence region"
        }, {
            regionIndex: 8,
            leftBorderIndex: 1,
            rightBorderIndex: 2,
            topBorderIndex: 4,
            bottomBorderIndex: 5,
            legalObjects: "cdehilmpqstv",
            regionName: "to mode region"
        }, {
            regionIndex: 9,
            leftBorderIndex: 1,
            rightBorderIndex: 2,
            topBorderIndex: 5,
            bottomBorderIndex: 6,
            legalObjects: "cdehilmpqstv",
            regionName: "bar region"
        }, {
            regionIndex: 10,
            leftBorderIndex: 1,
            rightBorderIndex: 2,
            topBorderIndex: 6,
            bottomBorderIndex: 7,
            legalObjects: "cdehilmpqstv",
            regionName: "dss events region"
        }]
    }
});
